---
# Install binaries
- name: "Get Smallstep"
  get_url:
    dest: "~{{ansible_user}}/step-certificates_0.13.3_amd64.deb"
    url: "https://github.com/smallstep/certificates/releases/download/v0.13.3/step-certificates_0.13.3_amd64.deb"
- name: "Get Smallstep CLI"
  get_url:
    dest: "~{{ansible_user}}/step-cli_0.13.3_amd64.deb"
    url: "https://github.com/smallstep/cli/releases/download/v0.13.3/step-cli_0.13.3_amd64.deb"
- name: Install smallstep and smallstep cli
  become: true
  apt:
    deb:  "~{{ansible_user}}/{{item}}"
  with_items:
    - "step-certificates_0.13.3_amd64.deb"
    - "step-cli_0.13.3_amd64.deb"
- name: "Install golang dependency"
  become: true
  apt:
    name: "golang"
    state: present

# Pre Init config management
- name: "Create {{step_user}} user"
  become: true
  user:
    user: "{{step_user}}"
    password: ""
    shell: /sbin/nologin
    home: "{{step_home}}"
    move_home: yes
    create_home: yes
    system: yes
- name: "Ensure /etc/step-ca dir exists"
  become: true
  file:
    path: "/etc/step-ca"
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: "Copy password file"
  become: true
  copy:
    src: generated-password
    dest: /etc/step-ca/password.txt
    mode: '0600'
    owner: "{{step_user}}"
    group: "{{step_user}}"

# Init CA Server
- name: "Determine if ca server already initialized"
  become_user: "{{step_user}}"
  stat:
    path: "{{step_path}}"
  register: step_dir
- name: "Init ca server"
  become_user: "{{step_user}}"
  command:
    argv:
      - "/usr/bin/step"
      - "ca"
      - "init"
      - "-name"
      - "playground"
      - "-dns"
      - "localhost,ca-server.michaelasnes.com"
      - "-address"
      - ":443"
      - "-provisioner"
      - "playground-ca-1"
      - "-password-file"
      - "/etc/step-ca/password.txt"
  when: not step_dir.stat.exists

# Enable and run CA Server
- name: Setup Systemd Unit File for CA Server
  become: true
  template:
    src: step-ca.service.j2
    dest: /etc/systemd/system/step-ca.service

- name: Enable and Run Step CA Server
  systemd:
    name: step-ca.service
    state: restarted
    enabled: yes
    daemon_reload: yes
