- hosts: ca_server
  remote_user: admin
  tasks:
    - name: "Latest packages"
      become: true
      apt:
        name: "*"
        state: "latest"
    - name: "Get Smallstep"
      get_url:
        dest: "/home/admin/step-certificates_0.13.3_amd64.deb"
        url: "https://github.com/smallstep/certificates/releases/download/v0.13.3/step-certificates_0.13.3_amd64.deb"
    - name: "Get Smallstep CLI"
      get_url:
        dest: "/home/admin/step-cli_0.13.3_amd64.deb" 
        url: "https://github.com/smallstep/cli/releases/download/v0.13.3/step-cli_0.13.3_amd64.deb"
    - name: Install smallstep and smallstep cli
      become: true
      apt:
        deb:  "/home/admin/{{item}}"
      with_items:
        - "step-certificates_0.13.3_amd64.deb"
        - "step-cli_0.13.3_amd64.deb"
    - name: "Install golang dependency"
      become: true
      apt:
        name: "golang"
        state: present
    - name: "Copy password file"
      copy:
        src: generated-password
        dest: ~/
       mode: 0600
    - name: "Determine if ca server already initialized"
      stat:
        path: ~/.step
      register: step_folder
    - name: "Init ca server"
      command:
        argv:
          - "/usr/bin/step"
          - "ca"
          - "init"
          - "-name"
          - "playground"
          - "-dns"
          - "ca-server.micahelasnes.io,log-server.michaelasnes.io"
          - "-address"
          - ":443"
          - "-provisioner"
          - "playground-ca-1"
          - "-password-file"
          - "~/generated-password"
      when: not step_folder.stat.exists
